Repository dotnet/razor, pull requests merged in 2019-09, with the labels that each got.

#1146 [Infrastructure] Install procdump and capture dumps on build hangs
  azure-pipelines.yml
  eng/common/templates/job/job.yml
  eng/scripts/FinishDumpCollectionForHangingBuilds.ps1
  eng/scripts/InstallProcDump.ps1
  eng/scripts/StartDumpCollectionForHangingBuilds.ps1
  src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/MSBuildProcessManager.cs
  src/Razor/test/Microsoft.NET.Sdk.Razor.Test/Microsoft.NET.Sdk.Razor.Test.csproj
Labels: area-infrastructure, tell-mode

#1149 [Infrastructure] Fix assembly metadata key
  src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/MSBuildProcessManager.cs
  src/Razor/test/Microsoft.NET.Sdk.Razor.Test/Microsoft.NET.Sdk.Razor.Test.csproj
Labels: tell-mode

#1168 Update branding to 3.0.1
  eng/Versions.props
Labels: area-platform

#1166 [release/3.0] Switch to embedded package icon
  Directory.Build.props
  global.json
  packageIcon.png
  src/Razor/src/Microsoft.NET.Sdk.Razor/Microsoft.NET.Sdk.Razor.csproj
  src/Razor/src/Microsoft.NET.Sdk.Razor/Microsoft.NET.Sdk.Razor.nuspec
  src/Razor/test/Microsoft.AspNetCore.Mvc.Razor.Extensions.Test/Microsoft.AspNetCore.Mvc.Razor.Extensions.Test.csproj
  src/Razor/test/Microsoft.AspNetCore.Mvc.Razor.Extensions.Version1_X.Test/Microsoft.AspNetCore.Mvc.Razor.Extensions.Version1_X.Test.csproj
  src/Razor/test/Microsoft.AspNetCore.Mvc.Razor.Extensions.Version2_X.Test/Microsoft.AspNetCore.Mvc.Razor.Extensions.Version2_X.Test.csproj
  src/Razor/test/RazorLanguage.Test/Microsoft.AspNetCore.Razor.Language.Test.csproj
Labels: area-infrastructure

#1183 Update branding to 3.1.0-preview2
  eng/Versions.props
Labels: area-platform
