Repository dotnet/razor, pull requests merged in 2019-11, with the labels that each got.

#1287 Blazor support for VS4Mac
  src/Razor/src/Microsoft.VisualStudio.Editor.Razor/BackgroundDocumentGenerator.cs
  src/Razor/src/Microsoft.VisualStudio.Editor.Razor/DefaultVisualStudioMacDocumentInfoFactory.cs
  src/Razor/src/Microsoft.VisualStudio.Editor.Razor/RazorDynamicFileInfoProvider.cs
  src/Razor/src/Microsoft.VisualStudio.Editor.Razor/VisualStudioMacDocumentInfoFactory.cs
  src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/ProjectSystem/DefaultRazorDynamicFileInfoProvider.cs
  src/Razor/src/Microsoft.VisualStudio.Mac.LanguageServices.Razor/BackgroundDocumentGenerator.cs
  src/Razor/src/Microsoft.VisualStudio.Mac.LanguageServices.Razor/ProjectSystem/DefaultRazorDynamicDocumentInfoProvider.cs
  src/Razor/src/Microsoft.VisualStudio.Mac.LanguageServices.Razor/ProjectSystem/RazorDynamicDocumentInfoProvider.cs
  src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/DocumentGenerator/BackgroundDocumentGeneratorTest.cs
  src/Razor/test/Microsoft.VisualStudio.Mac.LanguageServices.Razor.Test/ProjectSystem/DefaultRazorDocumentInfoProviderTest.cs
Labels: area-blazor, tooling-only

#1288 Remove legacy Razor directive completion
  eng/Versions.props
  src/Razor/src/Microsoft.VisualStudio.Editor.Razor/BackgroundDocumentGenerator.cs
  src/Razor/src/Microsoft.VisualStudio.Editor.Razor/Completion/RazorDirectiveCompletionProvider.cs
  src/Razor/src/Microsoft.VisualStudio.Editor.Razor/DefaultCodeDocumentProvider.cs
  src/Razor/src/Microsoft.VisualStudio.Editor.Razor/DefaultTextBufferProvider.cs
  src/Razor/src/Microsoft.VisualStudio.Editor.Razor/DefaultVisualStudioMacDocumentInfoFactory.cs
  src/Razor/src/Microsoft.VisualStudio.Editor.Razor/RazorCodeDocumentProvider.cs
  src/Razor/src/Microsoft.VisualStudio.Editor.Razor/RazorDynamicFileInfoProvider.cs
  src/Razor/src/Microsoft.VisualStudio.Editor.Razor/RazorTextBufferProvider.cs
  src/Razor/src/Microsoft.VisualStudio.Editor.Razor/VisualStudioMacDocumentInfoFactory.cs
  src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/ProjectSystem/DefaultRazorDynamicFileInfoProvider.cs
  src/Razor/src/Microsoft.VisualStudio.Mac.LanguageServices.Razor/ProjectSystem/DefaultRazorDynamicDocumentInfoProvider.cs
  src/Razor/src/Microsoft.VisualStudio.Mac.LanguageServices.Razor/RazorDocumentControllerExtension.cs
  src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/Completion/RazorDirectiveCompletionProviderTest.cs
  src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/DefaultCodeDocumentProviderTest.cs
  src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/DefaultTextBufferProviderTest.cs
  src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/DocumentGenerator/BackgroundDocumentGeneratorTest.cs
  src/Razor/test/Microsoft.VisualStudio.Mac.LanguageServices.Razor.Test/ProjectSystem/DefaultRazorDocumentInfoProviderTest.cs
Labels: tooling-only

#1293 Fix Razor < 3.0 projects null-refing when WorkspaceChanged events fire.
  src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/WorkspaceProjectStateChangeDetector.cs
  src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/ProjectSystem/WorkspaceProjectStateChangeDetectorTest.cs
Labels: tooling-only

#1314 Fix Razor VSCode C# completions at beginning of the line.
  src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/RazorCompletionItemProvider.ts
Labels: tooling-only

#1310 Ensure 3.0 Razor SDKs don't add duplicate Razor document declarations/files.
  src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer.Common/DefaultRemoteTextLoaderFactory.cs
  src/Razor/src/Microsoft.AspNetCore.Razor.OmniSharpPlugin/PrecompiledRazorPageSuppressor.cs
  src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/RazorDocumentManager.ts
  src/Razor/test/Microsoft.AspNetCore.Razor.OmniSharpPlugin.Test/BackgroundDocumentProcessedPublisherTest.cs
  src/Razor/test/Microsoft.AspNetCore.Razor.OmniSharpPlugin.Test/OmniSharpTestBase.cs
  src/Razor/test/Microsoft.AspNetCore.Razor.OmniSharpPlugin.Test/OmniSharpWorkspaceTestBase.cs
  src/Razor/test/Microsoft.AspNetCore.Razor.OmniSharpPlugin.Test/PrecompiledRazorPageSuppressorTest.cs
Labels: tooling-only

#1309 Fix project state improperly caching during matching RootNamespace & ProjectWorkspaceState updates.
  src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/ProjectState.cs
  src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/ProjectSystem/ProjectStateTest.cs
  src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/ProjectSystem/DefaultProjectSnapshotManagerTest.cs
Labels: tooling-only

#1294 Fix Language Server diagnostics timer publish requiring foreground thread
  src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer.Common/BackgroundDocumentGenerator.cs
  src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer.Common/DefaultProjectEngineFactory.cs
  src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer.Common/DefaultRemoteTextLoaderFactory.cs
  src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer.Common/DocumentProcessedListener.cs
  src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer.Common/ProjectEngineFactory_3_0.cs
  src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer.Common/RemoteTextLoaderFactory.cs
  src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultGeneratedCodeContainerStore.cs
  src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultRemoteTextLoaderFactory.cs
  src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Microsoft.AspNetCore.Razor.LanguageServer.csproj
  src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Program.cs
  src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorDiagnosticsPublisher.cs
  src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/UnsynchronizableContentDocumentProcessedListener.cs
  src/Razor/src/Microsoft.AspNetCore.Razor.OmniSharpPlugin.StrongNamed/DefaultOmniSharpProjectSnapshotManager.cs
  src/Razor/src/Microsoft.AspNetCore.Razor.OmniSharpPlugin.StrongNamed/DefaultOmniSharpProjectSnapshotManagerAccessor.cs
  src/Razor/src/Microsoft.AspNetCore.Razor.OmniSharpPlugin.StrongNamed/OmniSharpBackgroundDocumentGenerator.cs
  src/Razor/src/Microsoft.AspNetCore.Razor.OmniSharpPlugin.StrongNamed/OmniSharpDocumentProcessedListener.cs
  src/Razor/src/Microsoft.AspNetCore.Razor.OmniSharpPlugin.StrongNamed/OmniSharpDocumentSnapshot.cs
  src/Razor/src/Microsoft.AspNetCore.Razor.OmniSharpPlugin.StrongNamed/OmniSharpProjectChangeEventArgs.cs
  src/Razor/src/Microsoft.AspNetCore.Razor.OmniSharpPlugin.StrongNamed/OmniSharpProjectSnapshotManagerBase.cs
  src/Razor/src/Microsoft.AspNetCore.Razor.OmniSharpPlugin/BackgroundDocumentProcessedPublisher.cs
  src/Razor/src/Microsoft.AspNetCore.Razor.OmniSharpPlugin/ComponentRefreshTrigger.cs
  src/Razor/src/Microsoft.AspNetCore.Razor.OmniSharpPlugin/DefaultUpdateBufferDispatcher.cs
  src/Razor/src/Microsoft.AspNetCore.Razor.OmniSharpPlugin/DocumentChangedSynchronizationService.cs
  src/Razor/src/Microsoft.AspNetCore.Razor.OmniSharpPlugin/EmptyTextLoader.cs
  src/Razor/src/Microsoft.AspNetCore.Razor.OmniSharpPlugin/LatestProjectConfigurationProvider.cs
  src/Razor/src/Microsoft.AspNetCore.Razor.OmniSharpPlugin/MSBuildProjectDocumentChangeDetector.cs
  src/Razor/src/Microsoft.AspNetCore.Razor.OmniSharpPlugin/OmniSharpStrongNamedExports.cs
  src/Razor/src/Microsoft.AspNetCore.Razor.OmniSharpPlugin/PrecompiledRazorPageSuppressor.cs
  src/Razor/src/Microsoft.AspNetCore.Razor.OmniSharpPlugin/RazorFileChangeEventArgs.cs
  src/Razor/src/Microsoft.AspNetCore.Razor.OmniSharpPlugin/TagHelperRefreshTrigger.cs
  src/Razor/src/Microsoft.AspNetCore.Razor.OmniSharpPlugin/UpdateBufferDispatcher.cs
  src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/RazorDocumentManager.ts
  src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/RazorLanguageServiceClient.ts
  src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/WorkspaceProjectStateChangeDetector.cs
  src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Common.Test/BackgroundDocumentGeneratorTest.cs
  src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/RazorDiagnosticsPublisherTest.cs
  src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/UnsynchronizableContentDocumentProcessedListenerTest.cs
  src/Razor/test/Microsoft.AspNetCore.Razor.OmniSharpPlugin.Test/BackgroundDocumentProcessedPublisherTest.cs
  src/Razor/test/Microsoft.AspNetCore.Razor.OmniSharpPlugin.Test/ComponentRefreshTriggerTest.cs
  src/Razor/test/Microsoft.AspNetCore.Razor.OmniSharpPlugin.Test/DefaultProjectChangePublisherTest.cs
  src/Razor/test/Microsoft.AspNetCore.Razor.OmniSharpPlugin.Test/LatestProjectConfigurationProviderTest.cs
  src/Razor/test/Microsoft.AspNetCore.Razor.OmniSharpPlugin.Test/MSBuildProjectDocumentChangeDetectorTest.cs
  src/Razor/test/Microsoft.AspNetCore.Razor.OmniSharpPlugin.Test/OmniSharpTestBase.cs
  src/Razor/test/Microsoft.AspNetCore.Razor.OmniSharpPlugin.Test/OmniSharpWorkspaceTestBase.cs
  src/Razor/test/Microsoft.AspNetCore.Razor.OmniSharpPlugin.Test/PrecompiledRazorPageSuppressorTest.cs
  src/Razor/test/Microsoft.AspNetCore.Razor.OmniSharpPlugin.Test/TagHelperRefreshTriggerTest.cs
  src/Razor/test/Microsoft.AspNetCore.Razor.OmniSharpPlugin.Test/TestOmniSharpWorkspace.cs
  src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/ProjectSystem/WorkspaceProjectStateChangeDetectorTest.cs
Labels: tooling-only

#1341 Enable building `blazor-wasm` branch
  azure-pipelines.yml
Labels: area-blazor
