Repository dotnet/razor, pull requests merged in 2020-02, with the labels that each got.

#1557 [master] Switch to Windows Server queues
  azure-pipelines.yml
Labels: area-infrastructure

#1233 Added back 1.x tests
  src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.FunctionalTest/tests/Completions1_0.test.ts
  src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.FunctionalTest/tests/TestUtil.ts
  src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/BuildIntegrationTest11.cs
  src/Razor/test/Microsoft.NET.Sdk.Razor.Test/Microsoft.NET.Sdk.Razor.Test.csproj
  src/Razor/test/testapps/RestoreTestProjects/RestoreTestProjects.csproj
  src/Razor/test/testapps/SimpleMvc11/Program.cs
  src/Razor/test/testapps/SimpleMvc11/SimpleMvc11.csproj
  src/Razor/test/testapps/SimpleMvc11/Views/Home/Index.cshtml
  src/Razor/test/testapps/SimpleMvc11/Views/Shared/_Layout.cshtml
  src/Razor/test/testapps/SimpleMvc11/Views/_ViewImports.cshtml
  src/Razor/test/testapps/SimpleMvc11/Views/_ViewStart.cshtml
  src/Razor/test/testapps/SimpleMvc11NetFx/Program.cs
  src/Razor/test/testapps/SimpleMvc11NetFx/SimpleMvc11NetFx.csproj
  src/Razor/test/testapps/SimpleMvc11NetFx/Views/Home/Index.cshtml
  src/Razor/test/testapps/SimpleMvc11NetFx/Views/Shared/_Layout.cshtml
  src/Razor/test/testapps/SimpleMvc11NetFx/Views/_ViewImports.cshtml
  src/Razor/test/testapps/SimpleMvc11NetFx/Views/_ViewStart.cshtml
Labels: auto-merge, tell-mode

#1556 [release/3.1] Switch to Windows Server queues
  azure-pipelines.yml
Labels: area-infrastructure, tell-mode

#1588 Suppress warnings about depending on non-stable versions of packages
  src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer.Common/Microsoft.AspNetCore.Razor.LanguageServer.Common.csproj
Labels: area-infrastructure, tell-mode

#1620 Decouple from dotnet/extensions
  eng/Version.Details.xml
  eng/Versions.props
Labels: area-infrastructure
