Repository dotnet/razor, pull requests merged in 2020-01, with the labels that each got.

#1471 Update branding to 3.1.2
  azure-pipelines.yml
  eng/Version.Details.xml
  eng/Versions.props
Labels: area-infrastructure

#1415 [Static web assets][Fixes #AspNetCore/17079] PublishSingleFile results in 404 errors for Nuget components
  src/Razor/src/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Microsoft.NET.Sdk.Razor.StaticWebAssets.targets
  src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/MSBuildIntegrationTestBase.cs
  src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/StaticWebAssetsIntegrationTest.cs
Labels: Servicing-approved, area-blazor

#1394 Load the netcoreapp3.1 compiled task when running in Core MSBuild
  src/Razor/src/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Sdk.Razor.CurrentVersion.targets
  src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/BuildIntrospectionTest.cs
  src/Razor/test/Microsoft.NET.Sdk.Razor.Test/Microsoft.NET.Sdk.Razor.Test.csproj
  src/Razor/test/testapps/RazorTest.Introspection.targets
Labels: Servicing-approved

#1442 [StaticWebAssets][Fixes #AspNetCore/17426] Publish no build doesn't copy static web assets from referenced projects
  src/Razor/src/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Microsoft.NET.Sdk.Razor.StaticWebAssets.targets
  src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/StaticWebAssetsIntegrationTest.cs
Labels: Servicing-approved, area-blazor

#1383 [StaticWebAssets] Updates manifest generation to allow multiple content roots under the same base path for a single project
  src/Razor/src/Microsoft.NET.Sdk.Razor/GenerateStaticWebAssetsManifest.cs
  src/Razor/src/Microsoft.NET.Sdk.Razor/ValidateStaticWebAssetsUniquePaths.cs
  src/Razor/src/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Microsoft.NET.Sdk.Razor.StaticWebAssets.targets
  src/Razor/test/Microsoft.NET.Sdk.Razor.Test/GenerateAspNetCoreStaticAssetsManifestTest.cs
  src/Razor/test/Microsoft.NET.Sdk.Razor.Test/ValidateStaticWebAssetsUniquePathsTest.cs
Labels: Servicing-approved
