Repository dotnet/razor, pull requests merged in 2020-05, with the labels that each got.

#1888 Update branding to Preview6
  eng/Versions.props
Labels: area-infrastructure

#1823 [release/3.1] Move SDL validation to ringed release
  azure-pipelines.yml
  eng/sdl-tsa-vars.config
Labels: area-infrastructure, tell-mode

#1905 Conform to new Semantic colorization system
  src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer.Common/LanguageServerConstants.cs
  src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/ISemanticTokenHandler.cs
  src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/RazorSemanticTokenEndpoint.cs
  src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/SemanticTokensCapability.cs
  src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/package.json
  src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/yarn.lock
  src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/package.json
  src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/Html/HtmlTagCompletionProvider.ts
  src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/ProposedApisFeature.ts
  src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/RazorCompletionItemProvider.ts
  src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/RazorLanguageServiceClient.ts
  src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/Semantic/RazorDocumentSemanticTokensProvider.ts
  src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/extension.ts
  src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/vscode.proposed.d.ts
  src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/vscodeAdapter.ts
  src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/yarn.lock
  src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Test/package.json
  src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Test/tests/Mocks/TestVSCodeApi.ts
  src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Test/yarn.lock
  src/Razor/test/VSCode.FunctionalTest/package.json
  src/Razor/test/VSCode.FunctionalTest/yarn.lock
Labels: auto-merge

#1923 Skip Rebuild_Success_RecreatesManifestAndCache
  src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/StaticWebAssetsIntegrationTest.cs
Labels: auto-merge
