Repository dotnet/razor, pull requests merged in 2020-04, with the labels that each got.

#1741 [release/5.0-preview3] Don't build windows debug internally
  azure-pipelines.yml
Labels: Servicing-approved, area-infrastructure, ask-mode

#1744 Ingest new packages from dotnet/runtime
  eng/Version.Details.xml
  eng/Versions.props
Labels: area-infrastructure

#1766 [release/3.1] Don't run Code Check in official builds
  azure-pipelines.yml
Labels: area-infrastructure, tell-mode

#1767 [release/5.0-preview3] Don't run Code Check in official builds
  azure-pipelines.yml
Labels: area-infrastructure, tell-mode

#1808 Update branding to preview5
  eng/Versions.props
Labels: area-infrastructure

#1810 Use newer post-build.yml than Arcade provides
  eng/common/templates/post-build/post-build.yml
Labels: area-infrastructure
