Repository dotnet/razor, pull requests merged in 2021-12, with the labels that each got.

#5832 Revert "Call AdviseRunningDocTableEvents on UI thread. (#5783)"
  src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Documents/VisualStudioEditorDocumentManager.cs
Labels: auto-merge

#5862 Merging internal commits for release/3.1
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
  global.json
Labels: area-infrastructure

#5848 Fix CI package restore flakiness (hopefully).
  eng/Versions.props
  src/Razor/src/Directory.Build.props
  src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/DefaultProjectWorkspaceStateGenerator.cs
  src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/Microsoft.CodeAnalysis.Remote.Razor.csproj
  src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Microsoft.VisualStudio.LanguageServerClient.Razor.csproj
  src/Razor/src/Microsoft.VisualStudio.LiveShare.Razor/Microsoft.VisualStudio.LiveShare.Razor.csproj
  src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/BatchingWorkQueueTest.cs
  src/Razor/test/Microsoft.CodeAnalysis.Remote.Razor.Test/Microsoft.CodeAnalysis.Remote.Razor.Test.csproj
  src/Razor/test/Microsoft.VisualStudio.LiveShare.Razor.Test/Microsoft.VisualStudio.LiveShare.Razor.Test.csproj
Labels: auto-merge

#5867 Upgrade yarn source build tools to 122.10
  eng/Tools.props
Labels: auto-merge

#5885 Blazor WASM Debug Proxy Updates
  src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.BlazorWasmDebuggingExtension/BlazorDebugProxy/README.md
  src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.BlazorWasmDebuggingExtension/README.dev.md
  src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.BlazorWasmDebuggingExtension/README.md
  src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.BlazorWasmDebuggingExtension/package.json
  src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.BlazorWasmDebuggingExtension/scripts/retrieveDebugProxy.js
  src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.BlazorWasmDebuggingExtension/src/acquireDotnetInstall.ts
  src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.BlazorWasmDebuggingExtension/src/extension.ts
  src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.BlazorWasmDebuggingExtension/yarn.lock
  src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/package.json
  src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/src/extension.ts
  src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/yarn.lock
  src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/package.json
  src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/BlazorDebug/BlazorDebugConfigurationProvider.ts
  src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/BlazorDebug/TerminateDebugHandler.ts
  src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/CodeActions/RazorCodeActionRunner.ts
  src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/RazorLanguageServerClient.ts
  src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/extension.ts
  src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/tsconfig.json
  src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/yarn.lock
  src/Razor/src/rzls/Program.cs
  src/Razor/src/rzls/rzls.csproj
Labels: auto-merge, vscode
