Repository dotnet/razor, pull requests merged in 2021-10, with the labels that each got.

#4403 Avoid async void method in RazorLSPTextViewConnectionListener
  src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLSPTextViewConnectionListener.cs
Labels: auto-merge

#4605 Fix C# snippets being included in completion.
  src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/CompletionHandler.cs
Labels: Needs Approval

#4239 Switch to 1ES servicing pools in release/3.1
  azure-pipelines.yml
Labels: area-infrastructure
