Repository dotnet/razor, pull requests merged in 2022-08, with the labels that each got.

#6674 Actually add MonoDevelop.TextEditor dependency
  src/Razor/src/Microsoft.VisualStudio.Mac.RazorAddin/Microsoft.VisualStudio.Mac.RazorAddin.csproj
Labels: auto-merge

#6676 Update branding to 3.1.29
  eng/Versions.props
Labels: area-infrastructure, auto-merge

#6683 Don't swallow exceptions during completion.
  src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/AggregateCompletionListProvider.cs
  src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/AggregateCompletionListProviderTest.cs
  src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/RazorCompletionEndpointTest.cs
Labels: auto-merge

#6695 Merging internal commits for release/3.1
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
  global.json
Labels: area-infrastructure

#6700 Single server go to definition
  src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer.Common/RazorLanguageServerCustomMessageTargets.cs
  src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer.Protocol/DelegatedTypes.cs
  src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer.Protocol/IDelegatedParams.cs
  src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/AbstractRazorDelegatingEndpoint.cs
  src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultRazorDocumentMappingService.cs
  src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Definition/RazorDefinitionEndpoint.cs
  src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DocumentContext.cs
  src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Hover/RazorHoverEndpoint.cs
  src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorDocumentMappingService.cs
  src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Refactoring/RenameEndpoint.cs
  src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultRazorLanguageServerCustomMessageTarget.cs
  src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/InitializeHandler.cs
  src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLanguageServerCustomMessageTarget.cs
  src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Definition/RazorDefinitionEndpointTest.cs
  src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Hover/DefaultRazorHoverInfoServiceTest.cs
  src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Refactoring/RenameEndpointTest.cs
  src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/TestClient.cs
  src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/TestProjectSnapshotManagerAccessor.cs
  src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/TestResponseRouterReturn.cs
Labels: auto-merge
