Repository dotnet/razor, pull requests merged in 2024-06, with the labels that each got.

#10444 Enable 1ES's SBOM generation
  azure-pipelines-official.yml
Labels: area-infrastructure

#10440 Fix a tag helper test
  src/Compiler/test/Microsoft.NET.Sdk.Razor.SourceGenerators.Tests/RazorSourceGeneratorTagHelperTests.cs
  src/Compiler/test/Microsoft.NET.Sdk.Razor.SourceGenerators.Tests/TestFiles/RazorSourceGeneratorTagHelperTests/EscapedIdentifierInRazorBlock/Views_Home_Index.html
Labels: test scenario, area-compiler

#10476 Do not create insertions as drafts
  eng/config/PublishData.json
Labels: area-infrastructure

#10504 Fix APIScan authentication
  azure-pipelines-compliance.yml
Labels: area-infrastructure

#10506 Remove ITextBuffer and ITextDocument
  src/Compiler/Microsoft.AspNetCore.Razor.Language/test/Legacy/CSharpTokenizerTestBase.cs
  src/Compiler/Microsoft.AspNetCore.Razor.Language/test/Legacy/DirectiveCSharpTokenizerTest.cs
  src/Compiler/Microsoft.AspNetCore.Razor.Language/test/Legacy/DirectiveHtmlTokenizerTest.cs
  src/Compiler/Microsoft.AspNetCore.Razor.Language/test/Legacy/HtmlTokenizerTestBase.cs
  src/Compiler/Microsoft.AspNetCore.Razor.Language/test/Legacy/TokenizerTestBase.cs
  src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/Legacy/CSharpLanguageCharacteristics.cs
  src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/Legacy/CSharpTokenizer.cs
  src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/Legacy/DirectiveCSharpTokenizer.cs
  src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/Legacy/DirectiveHtmlTokenizer.cs
  src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/Legacy/FirstDirectiveCSharpLanguageCharacteristics.cs
  src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/Legacy/FirstDirectiveHtmlLanguageCharacteristics.cs
  src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/Legacy/HtmlLanguageCharacteristics.cs
  src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/Legacy/HtmlTokenizer.cs
  src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/Legacy/ITextBuffer.cs
  src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/Legacy/ITextDocument.cs
  src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/Legacy/LanguageCharacteristics.cs
  src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/Legacy/ParserContext.cs
  src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/Legacy/SeekableTextReader.cs
  src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/Legacy/Tokenizer.cs
  src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/Legacy/TokenizerView.cs
Labels: area-compiler

#10527 Update config for snap
  eng/Versions.props
  eng/config/PublishData.json
Labels: area-infrastructure

#10543 Enable TSA
  azure-pipelines-official.yml
  eng/TSAConfig.gdntsa
Labels: area-infrastructure

#10556 Update insertion config
  eng/config/PublishData.json
Labels: area-infrastructure
