Repository dotnet/razor, pull requests merged in 2024-04, with the labels that each got.

#10181 Handle whitespace after code block in `@:`
  src/Compiler/Microsoft.AspNetCore.Razor.Language/test/Legacy/HtmlBlockTest.cs
  src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/ParserTests/HtmlBlockTest/TextAfterCodeBlockInMarkupTransition_01.cspans.txt
  src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/ParserTests/HtmlBlockTest/TextAfterCodeBlockInMarkupTransition_01.stree.txt
  src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/ParserTests/HtmlBlockTest/TextAfterCodeBlockInMarkupTransition_02.cspans.txt
  src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/ParserTests/HtmlBlockTest/TextAfterCodeBlockInMarkupTransition_02.stree.txt
  src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/ParserTests/HtmlBlockTest/TextAfterCodeBlockInMarkupTransition_03.cspans.txt
  src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/ParserTests/HtmlBlockTest/TextAfterCodeBlockInMarkupTransition_03.stree.txt
  src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/ParserTests/HtmlBlockTest/TextAfterCodeBlockInMarkupTransition_04.cspans.txt
  src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/ParserTests/HtmlBlockTest/TextAfterCodeBlockInMarkupTransition_04.stree.txt
  src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/Legacy/HtmlMarkupParser.cs
  src/Compiler/test/Microsoft.NET.Sdk.Razor.SourceGenerators.Tests/RazorSourceGeneratorComponentTests.cs
  src/Compiler/test/Microsoft.NET.Sdk.Razor.SourceGenerators.Tests/TestFiles/RazorSourceGeneratorComponentTests/TextAfterCodeBlockInMarkupTransition/Views_Home_Index.html
Labels: area-compiler

#10240 Simplify pipelines
  azure-pipelines-official.yml
  azure-pipelines.yml
Labels: area-infrastructure

#10256 Replace deprecated CI images
  azure-pipelines-official.yml
Labels: area-infrastructure

#10288 Lower drop retention from 10 years to 3 months
  azure-pipelines-official.yml
Labels: area-infrastructure

#10310 Fix source mappings not appearing in fuse:
  src/Compiler/Microsoft.AspNetCore.Razor.Language/test/CodeGeneration/DesignTimeNodeWriterTest.cs
  src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/CodeGeneration/CodeWriterExtensions.cs
Labels: area-compiler, New Feature: Fuse
